auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Wendale的博客
url: http://weibo.com/wenhansd
feed: /atom.xml
author_info: <a href=“http://weibo.com/wenhansd”>Wendale</a>
